#!/bin/bash
# Self-hosting package (Phase E) -- generates the two values that are
# genuinely instance-specific secrets (not published defaults) into a
# .env file docker-compose.yml reads automatically. Safe to re-run: it
# never overwrites an existing .env, so your secrets stay stable across
# restarts.
set -euo pipefail

cd "$(dirname "$0")"

if [ -f .env ]; then
  echo ".env already exists -- leaving it alone. Delete it first if you want to regenerate."
  exit 0
fi

INTERNAL_SERVICE_TOKEN="$(openssl rand -hex 32)"
AI_KEY_ENCRYPTION_KEY="$(openssl rand -base64 32)"

cat > .env <<EOF
# Generated by generate-secrets.sh -- do not commit this file.
INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
AI_KEY_ENCRYPTION_KEY=${AI_KEY_ENCRYPTION_KEY}

# Optional: set your own Anthropic key here to enable AI features.
# Leave blank to run without them -- everything else works fine either way.
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-opus-4-8

# Optional: your company name, shown in the app.
COMPANY=My Company
EOF

echo "Wrote .env with a freshly generated INTERNAL_SERVICE_TOKEN and AI_KEY_ENCRYPTION_KEY."
echo "Edit .env to add ANTHROPIC_API_KEY if you want AI features enabled."
